spring:
  application:
    name: eblog
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
  # spring 静态资源扫描路径
  resources:
    static-locations: classpath:/static/
  freemarker:
    #指定freemarker的模板路径和模板的后缀
    template-loader-path: classpath:/templates/
    suffix: .ftl
    # 指定字符集
    charset: utf-8
    # 页面不加载缓存，修改即时生效
    cache: false
    #指定是否要暴露请求和会话属性
    expose-request-attributes: true
    expose-session-attributes: true
    settings:
      # 空值处理 加了这个引入就要写绝对路径
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: 0.##
  data:
    elasticsearch:
      repositories:
        enabled: true
  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 465
    auth: true
    username: codecrab@qq.com
    password: rubukrzxvthaidbg
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
file:
  upload:
    dir: ${user.dir}/upload
im:
  server:
    port: 9326
  user:
    default-avatar: https://img.imgdb.cn/item/603a412e5f4313ce2536582f.jpg,https://img.imgdb.cn/item/603a412e5f4313ce25365838.jpg,https://img.imgdb.cn/item/603a412e5f4313ce2536583a.jpg,https://img.imgdb.cn/item/60437b4a360785be54b9cd2a.jpg,https://img.imgdb.cn/item/60437b4a360785be54b9cd2f.jpg,https://img.imgdb.cn/item/60437b4a360785be54b9cd35.jpg,https://img.imgdb.cn/item/60437b4a360785be54b9cd3c.jpg,https://img.imgdb.cn/item/60437b4a360785be54b9cd44.jpg,https://img.imgdb.cn/item/60437b7e360785be54b9e5a5.jpg,https://img.imgdb.cn/item/60437b7e360785be54b9e5aa.jpg
